# Generated by Django 3.2.13 on 2022-11-10 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20221110_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_users',
        ),
        migrations.AddField(
            model_name='product',
            name='cart_users',
            field=models.ManyToManyField(null=True, related_name='cart_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='product',
            name='ddib_users',
        ),
        migrations.AddField(
            model_name='product',
            name='ddib_users',
            field=models.ManyToManyField(null=True, related_name='ddib_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
